### ISSUE TITLE
Gradle spring boot error : Invalid relative name: META-INF\ap4k\kubernetes.json

### ISSUE THREAD

**Issue by alexlungu10** [ap4k/ap4k#96] opened 2019-01-04 13:10 UTC
Hello, I've made a **Gradle** project with **Spring Boot** and I've added the gradle dependencies plus the kubernetes Annotations.

I receive this error:
**### Invalid relative name: META-INF\ap4k\kubernetes.json**

I've also tried with : @GeneratorOptions(outputPath = "myfile") , but same error.
The problem seems to be under:
AbstractAnnotationProcessor ---->  protected void write(String group, KubernetesList list) {
....
 FileObject json = processingEnv.getFiler().createResource(StandardLocation.CLASS_OUTPUT, PACKAGE, project.getResourceOutputPath() + File.separatorChar + String.format(FILENAME, group, JSON));
     It seems that the second argument for createResource() does not accept separators, please try to remove the separator an keep a simple filename maybe.
Thanks.

My app is simple:
@KubernetesApplication
@SpringBootApplication
public class KubernetesDemo2Application {
........

and the Gradle dependencies:
...
dependencies {
	implementation('org.springframework.boot:spring-boot-starter-web')
	testImplementation('org.springframework.boot:spring-boot-starter-test')
    annotationProcessor("io.ap4k:kubernetes-annotations:${ap4kVersion}")
    compileOnly("io.ap4k:kubernetes-annotations:${ap4kVersion}")
	
	annotationProcessor("io.ap4k:ap4k-core:${ap4kVersion}")
    compileOnly("io.ap4k:ap4k-core:${ap4kVersion}")
   
   // compile("io.ap4k:ap4k-spring-boot:${ap4kVersion}")
}

...
For build I've used Gradle 4.1 and 5.1. Save issue...

Thank you verry much !

**Comment by alexlungu10** [comment] 2019-01-04 13:14
some logs:
 Caused by: java.lang.IllegalArgumentException: Invalid relative name: META-INF\ap4k\kubernetes.json
        at com.sun.tools.javac.file.JavacFileManager.getFileForOutput(JavacFileManager.java:737)
        at com.sun.tools.javac.processing.JavacFiler.createResource(JavacFiler.java:429)
        at io.ap4k.processor.AbstractAnnotationProcessor.write(AbstractAnnotationProcessor.java:152)
        at io.ap4k.processor.AbstractAnnotationProcessor.lambda$write$0(AbstractAnnotationProcessor.java:96)
        at io.ap4k.processor.AbstractAnnotationProcessor.write(AbstractAnnotationProcessor.java:96)
        at io.ap4k.Session.onClose(Session.java:82)
        at io.ap4k.kubernetes.processor.KubernetesAnnotationProcessor.process(KubernetesAnnotationProcessor.java:51)

**Comment by alexlungu10** [comment] 2019-01-04 13:15
The problem is still active, plsease see the logs above. Thank you.

**Comment by iocanel** [comment] 2019-01-04 15:36
@alexlungu10: I assume that you have the same issue if you try to build the ap4k examples, right?

**Comment by alexlungu10** [comment] 2019-01-04 18:11
Hello Iocanel, and thank you for your response, yes, that's true. One example is working with Maven (if I press  the build button from IDE only). But I need a working example for Gradle with ap4k- annotations. Thanks !

**Comment by iocanel** [comment] 2019-01-04 20:57
@alexlungu10: I managed to reproduce the issue. It seems to be windows specific. 
I will have to deal with it in both ap4k and sundrio and release both. I'll try to do that over the weekend.

**Comment by iocanel** [comment] 2019-01-04 23:01
Released 0.1.3 which contains the fix.
I will close the issue, but please do reopen if anything has slipped my attention.

**Closed by iocanel** 2019-01-04 23:01 UTC

**Comment by alexlungu10** [comment] 2019-01-06 04:38
@iocanel  , Thank you for your fix  . I tested it in my project and is working fine. If you want I can commit my demo Spring-Boot Gradle project in the example area for Kubernetes annotations.  Maybe others will find useful in the future :)
